name: GSplugin
author: Projektteam Herbert
version: 0.1
main: com.github.herbert.gsplugin.GSplugin

commands:
   gs:
      description: Hauptbefehl für Grundstücke
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: Fehlende Berechtigung <permission>