name: MainPlugin
author: Projektteam Herbert
version: 0.1
main: com.github.herbert.MainPlugin

commands:
   gs:
      description: Hauptbefehl für Grundstücke
      usage: /<command> [test / test2]
      permission: <plugin name>.gs
      permission-message: Fehlende Berechtigung <permission>