name: GSplugin
author: Projektteam Herbert
version: 0.1
main: com.github.herbert.gsplugin.GSplugin

commands:
   gs:
      description: Hauptbefehl für Grundstücke
      usage: /<command> [test / test2]
      permission: gsplugin.test
      permission-message: Fehlende Berechtigung <permission>