name: MainPlugin
author: Projektteam Herbert
version: 0.1
main: com.github.herbert.MainPlugin

commands:
   gs:
      description: Hauptbefehl für WorldBlocks
      usage: /<command> [fehler]
      permission: <plugin name>.worldblocks
      permission-message: Fehlende Berechtigung <permission>