name: MainPlugin
author: Projektteam Herbert
version: 0.1
main: com.github.herbert.MainPlugin

commands:
   gs:
      description: Hauptbefehl für WorldBlocks
      usage: /<command> [fehler]
   ich:
      description: Befehl für Spieleraktionen
      usage: /<command> [fehler]